name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    name: test / ${{ matrix.os.name }} / zig ${{ matrix.zig-version }} / ${{ matrix.mode.name }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: "linux"
            runner: "ubuntu-latest"
          - name: "macos"
            runner: "macos-latest"
          - name: "windows"
            runner: "windows-latest"
        zig-version:
          - "0.12.0"
          - "0.12.1"
          - "0.13.0"
        mode:
          - name: debug
            options: ""
          - name: release safe
            options: "--release=safe"
          - name: release fast
            options: "--release=fast"
        include:
          - os: { name: windows }
            needs_external_nasm: true

    runs-on: ${{ matrix.os.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: ${{ matrix.needs_external_nasm }}
        name: Setup NASM
        uses: ilammy/setup-nasm@v1

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Test
        run: zig build test ${{ matrix.mode.options }} --summary all
